import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
 pt: {
 dashboard: 'Dashboard',
 dashboard_overview: 'Visão geral das suas finanças',
 transactions: 'Transações',
 accounts: 'Contas',
 investments: 'Investimentos',
 ai_assistant: 'Assistente IA',
 logout: 'Sair',
 settings: 'Configurações',
 total_balance: 'Saldo Total',
 income: 'Receitas',
 expenses: 'Despesas',
 expense: 'Despesa',
 connect_bank: 'Conectar Nova Instituição',
 my_accounts: 'Minhas Contas',
 welcome: 'Bem-vindo',
 recent_transactions: 'Transações Recentes',
 see_all: 'Ver todas',
 add_transaction: 'Adicionar',
 import: 'Importar',
 export: 'Exportar',
 search: 'Buscar...',
 loading: 'Carregando...',
 demo_mode: 'Modo Demo',
 cash_flow: 'Fluxo de Caixa',
 expenses_by_category: 'Gastos por Categoria',
 import_transactions_to_see_chart: 'Importe transações para ver o gráfico',
 no_expenses: 'Sem despesas',
 no_recent_transactions: 'Nenhuma transação recente',
 no_transactions_yet: 'Nenhuma transação ainda',
 overview: 'Visão Geral',
 monthly_summary: 'Resumo financeiro do mês',
 ai_insights: 'Insights IA',
 planning: 'Planejamento',
 vacation: 'Viagem de Férias',
 emergency_fund: 'Reserva de Emergência',
 new_goal: '+ Novo Objetivo',
 last_transactions: 'Últimas Transações',
 last_14_days: 'Últimos 14 dias',
 this_month: 'Este Mês',
 income_vs_expenses: 'Receitas vs Despesas (Últimos 14 dias)',
 loading_data: 'Carregando seus dados...',
 general: 'Geral',
 // Settings
 account_settings: 'Configurações da Conta',
 manage_preferences: 'Gerencie suas preferências e segurança',
 preferences: 'Preferências',
 security: 'Segurança',
 notifications: 'Notificações',
 appearance_language: 'Aparência e Idioma',
 app_theme: 'Tema do Aplicativo',
 theme_desc: 'Escolha entre modo claro e escuro',
 main_currency: 'Moeda Principal',
 currency_desc: 'Moeda usada nos relatórios',
 account_security: 'Segurança da Conta',
 email_address: 'Endereço de E-mail',
 change: 'Alterar',
 access_password: 'Senha de Acesso',
 reset: 'Redefinir',
 connected_devices: 'Dispositivos Conectados',
 this_device: 'Este dispositivo',
 active_now: 'Ativo agora',
 last_access: 'Último acesso',
 remove_device: 'Remover dispositivo',
 notification_prefs: 'Preferências de Notificação',
 news_title: 'Novidades do Smart Finance Hub',
 news_desc: 'Novas funcionalidades e as melhores dicas para transformar sua vida financeira para melhor.',
 premium_title: 'Informações sobre o Premium',
 premium_desc: 'Confirmação de pagamento, ativação do Premium, promoções e novidades dos planos.',
 financial_alerts_title: 'Alertas Financeiros',
 financial_alerts_desc: 'Lembretes sobre datas de vencimento, gastos, transferências, pagamentos, desempenho e objetivos.',
 important: 'Importante',
 security_notice: 'Notificações transacionais importantes (como redefinição de senha ou alertas de segurança) não podem ser desativadas para garantir a proteção da sua conta.',
 theme_changed: 'Tema alterado para',
 dark: 'Escuro',
 light: 'Claro',
 password_reset_sent: 'E-mail de redefinição de senha enviado!',
 password_reset_error: 'Erro ao enviar e-mail de redefinição.',
 device_removed: 'Dispositivo removido',
 simulation: 'Simulação',
 saved: 'Salvo com sucesso!',
 },
 en: {
 dashboard: 'Dashboard',
 dashboard_overview: 'Overview of your finances',
 transactions: 'Transactions',
 accounts: 'Accounts',
 investments: 'Investments',
 ai_assistant: 'AI Assistant',
 logout: 'Sign Out',
 settings: 'Settings',
 total_balance: 'Total Balance',
 income: 'Income',
 expenses: 'Expenses',
 expense: 'Expense',
 connect_bank: 'Connect New Bank',
 my_accounts: 'My Accounts',
 welcome: 'Welcome',
 recent_transactions: 'Recent Transactions',
 see_all: 'See all',
 add_transaction: 'Add',
 import: 'Import',
 export: 'Export',
 search: 'Search...',
 loading: 'Loading...',
 demo_mode: 'Demo Mode',
 cash_flow: 'Cash Flow',
 expenses_by_category: 'Expenses by Category',
 import_transactions_to_see_chart: 'Import transactions to see the chart',
 no_expenses: 'No expenses',
 no_recent_transactions: 'No recent transactions',
 no_transactions_yet: 'No transactions yet',
 overview: 'Overview',
 monthly_summary: 'Monthly financial summary',
 ai_insights: 'AI Insights',
 planning: 'Planning',
 vacation: 'Vacation Trip',
 emergency_fund: 'Emergency Fund',
 new_goal: '+ New Goal',
 last_transactions: 'Latest Transactions',
 last_14_days: 'Last 14 days',
 this_month: 'This Month',
 income_vs_expenses: 'Income vs Expenses (Last 14 days)',
 loading_data: 'Loading your data...',
 general: 'General',
 account_settings: 'Account Settings',
 manage_preferences: 'Manage your preferences and security',
 preferences: 'Preferences',
 security: 'Security',
 notifications: 'Notifications',
 appearance_language: 'Appearance & Language',
 app_theme: 'App Theme',
 theme_desc: 'Choose between light and dark mode',
 main_currency: 'Main Currency',
 currency_desc: 'Currency used in reports',
 account_security: 'Account Security',
 email_address: 'Email Address',
 change: 'Change',
 access_password: 'Password',
 reset: 'Reset',
 connected_devices: 'Connected Devices',
 this_device: 'This device',
 active_now: 'Active now',
 last_access: 'Last access',
 remove_device: 'Remove device',
 notification_prefs: 'Notification Preferences',
 news_title: 'Smart Finance Hub News',
 news_desc: 'New features and the best tips to improve your financial life.',
 premium_title: 'Premium Information',
 premium_desc: 'Payment confirmation, Premium activation, promotions and plan news.',
 financial_alerts_title: 'Financial Alerts',
 financial_alerts_desc: 'Due date reminders, spending, transfers, payments, performance and goals.',
 important: 'Important',
 security_notice: 'Important transactional notifications (like password reset or security alerts) cannot be disabled to ensure your account protection.',
 theme_changed: 'Theme changed to',
 dark: 'Dark',
 light: 'Light',
 password_reset_sent: 'Password reset email sent!',
 password_reset_error: 'Error sending reset email.',
 device_removed: 'Device removed',
 simulation: 'Simulation',
 saved: 'Saved successfully!',
 },
 es: {
 dashboard: 'Tablero',
 dashboard_overview: 'Resumen de sus finanzas',
 transactions: 'Transacciones',
 accounts: 'Cuentas',
 investments: 'Inversiones',
 ai_assistant: 'Asistente IA',
 logout: 'Cerrar Sesión',
 settings: 'Configuración',
 total_balance: 'Saldo Total',
 income: 'Ingresos',
 expenses: 'Gastos',
 expense: 'Gasto',
 connect_bank: 'Conectar Nuevo Banco',
 my_accounts: 'Mis Cuentas',
 welcome: 'Bienvenido',
 recent_transactions: 'Transacciones Recientes',
 see_all: 'Ver todas',
 add_transaction: 'Agregar',
 import: 'Importar',
 export: 'Exportar',
 search: 'Buscar...',
 loading: 'Cargando...',
 demo_mode: 'Modo Demo',
 cash_flow: 'Flujo de Caja',
 expenses_by_category: 'Gastos por Categoría',
 import_transactions_to_see_chart: 'Importe transacciones para ver el gráfico',
 no_expenses: 'Sin gastos',
 no_recent_transactions: 'No hay transacciones recientes',
 no_transactions_yet: 'Aún no hay transacciones',
 overview: 'Visión General',
 monthly_summary: 'Resumen financiero del mes',
 ai_insights: 'Insights IA',
 planning: 'Planificación',
 vacation: 'Viaje de Vacaciones',
 emergency_fund: 'Fondo de Emergencia',
 new_goal: '+ Nuevo Objetivo',
 last_transactions: 'Últimas Transacciones',
 last_14_days: 'Últimos 14 días',
 this_month: 'Este Mes',
 income_vs_expenses: 'Ingresos vs Gastos (Últimos 14 días)',
 loading_data: 'Cargando sus datos...',
 general: 'General',
 account_settings: 'Configuración de Cuenta',
 manage_preferences: 'Gestione sus preferencias y seguridad',
 preferences: 'Preferencias',
 security: 'Seguridad',
 notifications: 'Notificaciones',
 appearance_language: 'Apariencia e Idioma',
 app_theme: 'Tema de la App',
 theme_desc: 'Elija entre modo claro y oscuro',
 main_currency: 'Moneda Principal',
 currency_desc: 'Moneda usada en informes',
 account_security: 'Seguridad de la Cuenta',
 email_address: 'Correo Electrónico',
 change: 'Cambiar',
 access_password: 'Contraseña',
 reset: 'Restablecer',
 connected_devices: 'Dispositivos Conectados',
 this_device: 'Este dispositivo',
 active_now: 'Activo ahora',
 last_access: 'Último acceso',
 remove_device: 'Eliminar dispositivo',
 notification_prefs: 'Preferencias de Notificación',
 news_title: 'Novedades Smart Finance Hub',
 news_desc: 'Nuevas funcionalidades y los mejores consejos para mejorar su vida financiera.',
 premium_title: 'Información Premium',
 premium_desc: 'Confirmación de pago, activación Premium, promociones y novedades.',
 financial_alerts_title: 'Alertas Financieros',
 financial_alerts_desc: 'Recordatorios de vencimiento, gastos, transferencias, pagos, rendimiento y objetivos.',
 important: 'Importante',
 security_notice: 'Las notificaciones transaccionales importantes no se pueden desactivar para garantizar la protección de su cuenta.',
 theme_changed: 'Tema cambiado a',
 dark: 'Oscuro',
 light: 'Claro',
 password_reset_sent: '¡Email de restablecimiento enviado!',
 password_reset_error: 'Error al enviar email.',
 device_removed: 'Dispositivo eliminado',
 simulation: 'Simulación',
 saved: '¡Guardado con éxito!',
 },
 fr: {
 dashboard: 'Tableau de Bord',
 dashboard_overview: 'Aperçu de vos finances',
 transactions: 'Transactions',
 accounts: 'Comptes',
 investments: 'Investissements',
 ai_assistant: 'Assistant IA',
 logout: 'Déconnexion',
 settings: 'Paramètres',
 total_balance: 'Solde Total',
 income: 'Revenus',
 expenses: 'Dépenses',
 expense: 'Dépense',
 connect_bank: 'Connecter une Banque',
 my_accounts: 'Mes Comptes',
 welcome: 'Bienvenue',
 recent_transactions: 'Transactions Récentes',
 see_all: 'Voir tout',
 add_transaction: 'Ajouter',
 import: 'Importer',
 export: 'Exporter',
 search: 'Rechercher...',
 loading: 'Chargement...',
 demo_mode: 'Mode Démo',
 cash_flow: 'Flux de Trésorerie',
 expenses_by_category: 'Dépenses par Catégorie',
 import_transactions_to_see_chart: 'Importez des transactions pour voir le graphique',
 no_expenses: 'Aucune dépense',
 no_recent_transactions: 'Aucune transaction récente',
 no_transactions_yet: 'Aucune transaction pour le moment',
 overview: 'Aperçu',
 monthly_summary: 'Résumé financier du mois',
 ai_insights: 'Insights IA',
 planning: 'Planification',
 vacation: 'Voyage de Vacances',
 emergency_fund: "Fonds d'Urgence",
 new_goal: '+ Nouvel Objectif',
 last_transactions: 'Dernières Transactions',
 last_14_days: '14 derniers jours',
 this_month: 'Ce Mois',
 income_vs_expenses: 'Revenus vs Dépenses (14 derniers jours)',
 loading_data: 'Chargement de vos données...',
 general: 'Général',
 account_settings: 'Paramètres du Compte',
 manage_preferences: 'Gérez vos préférences et sécurité',
 preferences: 'Préférences',
 security: 'Sécurité',
 notifications: 'Notifications',
 appearance_language: 'Apparence et Langue',
 app_theme: "Thème de l'App",
 theme_desc: 'Choisissez entre mode clair et sombre',
 main_currency: 'Devise Principale',
 currency_desc: 'Devise utilisée dans les rapports',
 account_security: 'Sécurité du Compte',
 email_address: 'Adresse Email',
 change: 'Modifier',
 access_password: 'Mot de passe',
 reset: 'Réinitialiser',
 connected_devices: 'Appareils Connectés',
 this_device: 'Cet appareil',
 active_now: 'Actif maintenant',
 last_access: 'Dernier accès',
 remove_device: "Supprimer l'appareil",
 notification_prefs: 'Préférences de Notification',
 news_title: 'Nouveautés Smart Finance Hub',
 news_desc: 'Nouvelles fonctionnalités et meilleurs conseils pour améliorer votre vie financière.',
 premium_title: 'Informations Premium',
 premium_desc: 'Confirmation de paiement, activation Premium, promotions et nouveautés.',
 financial_alerts_title: 'Alertes Financières',
 financial_alerts_desc: "Rappels d'échéance, dépenses, virements, paiements, performances et objectifs.",
 important: 'Important',
 security_notice: 'Les notifications transactionnelles importantes ne peuvent pas être désactivées pour garantir la protection de votre compte.',
 theme_changed: 'Thème changé en',
 dark: 'Sombre',
 light: 'Clair',
 password_reset_sent: 'Email de réinitialisation envoyé !',
 password_reset_error: "Erreur lors de l'envoi de l'email.",
 device_removed: 'Appareil supprimé',
 simulation: 'Simulation',
 saved: 'Enregistré avec succès !',
 },
 cn: {
 dashboard: '仪表板',
 dashboard_overview: '您的财务概览',
 transactions: '交易',
 accounts: '账户',
 investments: '投资',
 ai_assistant: 'AI 助手',
 logout: '登出',
 settings: '设置',
 total_balance: '总余额',
 income: '收入',
 expenses: '支出',
 expense: '费用',
 connect_bank: '连接新银行',
 my_accounts: '我的账户',
 welcome: '欢迎',
 recent_transactions: '最近交易',
 see_all: '查看全部',
 add_transaction: '添加',
 import: '导入',
 export: '导出',
 search: '搜索...',
 loading: '加载中...',
 demo_mode: '演示模式',
 cash_flow: '现金流',
 expenses_by_category: '按类别支出',
 import_transactions_to_see_chart: '导入交易以查看图表',
 no_expenses: '无支出',
 no_recent_transactions: '无最近交易',
 no_transactions_yet: '暂无交易',
 overview: '概览',
 monthly_summary: '月度财务摘要',
 ai_insights: 'AI 洞察',
 planning: '规划',
 vacation: '假期旅行',
 emergency_fund: '应急基金',
 new_goal: '+ 新目标',
 last_transactions: '最新交易',
 last_14_days: '最近14天',
 this_month: '本月',
 income_vs_expenses: '收入 vs 支出（最近14天）',
 loading_data: '正在加载数据...',
 general: '一般',
 account_settings: '账户设置',
 manage_preferences: '管理您的偏好和安全',
 preferences: '偏好',
 security: '安全',
 notifications: '通知',
 appearance_language: '外观和语言',
 app_theme: '应用主题',
 theme_desc: '在亮色和暗色模式之间选择',
 main_currency: '主要货币',
 currency_desc: '报告中使用的货币',
 account_security: '账户安全',
 email_address: '电子邮箱',
 change: '更改',
 access_password: '密码',
 reset: '重置',
 connected_devices: '已连接设备',
 this_device: '此设备',
 active_now: '当前活跃',
 last_access: '最后访问',
 remove_device: '移除设备',
 notification_prefs: '通知偏好',
 news_title: 'Smart Finance Hub 新闻',
 news_desc: '新功能和改善财务生活的最佳建议。',
 premium_title: '高级版信息',
 premium_desc: '付款确认、高级版激活、促销和计划新闻。',
 financial_alerts_title: '财务提醒',
 financial_alerts_desc: '到期提醒、支出、转账、付款、绩效和目标。',
 important: '重要',
 security_notice: '重要的交易通知无法禁用，以确保您的账户安全。',
 theme_changed: '主题已更改为',
 dark: '暗色',
 light: '亮色',
 password_reset_sent: '密码重置邮件已发送！',
 password_reset_error: '发送重置邮件时出错。',
 device_removed: '设备已移除',
 simulation: '模拟',
 saved: '保存成功！',
 },
 hi: {
 dashboard: 'डैशबोर्ड',
 dashboard_overview: 'आपके वित्त का अवलोकन',
 transactions: 'लेनदेन',
 accounts: 'खाते',
 investments: 'निवेश',
 ai_assistant: 'AI सहायक',
 logout: 'लॉग आउट',
 settings: 'सेटिंग्स',
 total_balance: 'कुल शेष',
 income: 'आय',
 expenses: 'व्यय',
 expense: 'व्यय',
 connect_bank: 'नया बैंक जोड़ें',
 my_accounts: 'मेरे खाते',
 welcome: 'स्वागत',
 recent_transactions: 'हाल के लेनदेन',
 see_all: 'सभी देखें',
 add_transaction: 'जोड़ें',
 import: 'आयात',
 export: 'निर्यात',
 search: 'खोजें...',
 loading: 'लोड हो रहा है...',
 demo_mode: 'डेमो मोड',
 cash_flow: 'नकदी प्रवाह',
 expenses_by_category: 'श्रेणी के अनुसार व्यय',
 import_transactions_to_see_chart: 'चार्ट देखने के लिए लेनदेन आयात करें',
 no_expenses: 'कोई खर्चा नहीं',
 no_recent_transactions: 'हाल ही में कोई लेनदेन नहीं',
 no_transactions_yet: 'अभी तक कोई लेनदेन नहीं',
 overview: 'अवलोकन',
 monthly_summary: 'मासिक वित्तीय सारांश',
 ai_insights: 'AI अंतर्दृष्टि',
 planning: 'योजना',
 vacation: 'छुट्टी यात्रा',
 emergency_fund: 'आपातकालीन निधि',
 new_goal: '+ नया लक्ष्य',
 last_transactions: 'नवीनतम लेनदेन',
 last_14_days: 'पिछले 14 दिन',
 this_month: 'इस महीने',
 income_vs_expenses: 'आय vs व्यय (पिछले 14 दिन)',
 loading_data: 'डेटा लोड हो रहा है...',
 general: 'सामान्य',
 account_settings: 'खाता सेटिंग्स',
 manage_preferences: 'अपनी प्राथमिकताएं और सुरक्षा प्रबंधित करें',
 preferences: 'प्राथमिकताएं',
 security: 'सुरक्षा',
 notifications: 'सूचनाएं',
 appearance_language: 'दिखावट और भाषा',
 app_theme: 'ऐप थीम',
 theme_desc: 'लाइट और डार्क मोड में से चुनें',
 main_currency: 'मुख्य मुद्रा',
 currency_desc: 'रिपोर्ट में उपयोग की जाने वाली मुद्रा',
 account_security: 'खाता सुरक्षा',
 email_address: 'ईमेल पता',
 change: 'बदलें',
 access_password: 'पासवर्ड',
 reset: 'रीसेट',
 connected_devices: 'कनेक्टेड डिवाइस',
 this_device: 'यह डिवाइस',
 active_now: 'अभी सक्रिय',
 last_access: 'अंतिम एक्सेस',
 remove_device: 'डिवाइस हटाएं',
 notification_prefs: 'सूचना प्राथमिकताएं',
 news_title: 'Smart Finance Hub समाचार',
 news_desc: 'नई सुविधाएं और वित्तीय जीवन को बेहतर बनाने के सर्वोत्तम सुझाव।',
 premium_title: 'प्रीमियम जानकारी',
 premium_desc: 'भुगतान पुष्टि, प्रीमियम सक्रियण, प्रचार और योजना समाचार।',
 financial_alerts_title: 'वित्तीय अलर्ट',
 financial_alerts_desc: 'नियत तिथि अनुस्मारक, खर्च, स्थानांतरण, भुगतान, प्रदर्शन और लक्ष्य।',
 important: 'महत्वपूर्ण',
 security_notice: 'महत्वपूर्ण लेनदेन सूचनाएं अक्षम नहीं की जा सकतीं ताकि आपके खाते की सुरक्षा सुनिश्चित हो सके।',
 theme_changed: 'थीम बदली गई',
 dark: 'डार्क',
 light: 'लाइट',
 password_reset_sent: 'पासवर्ड रीसेट ईमेल भेजा गया!',
 password_reset_error: 'रीसेट ईमेल भेजने में त्रुटि।',
 device_removed: 'डिवाइस हटाया गया',
 simulation: 'सिमुलेशन',
 saved: 'सफलतापूर्वक सहेजा गया!',
 },
};

export function LanguageProvider({ children }) {
 const [language, setLanguage] = useState('pt');

 useEffect(() => {
 const stored = localStorage.getItem('sf_lang');
 if (stored) setLanguage(stored);
 }, []);

 const changeLanguage = (lang) => {
 setLanguage(lang);
 localStorage.setItem('sf_lang', lang);
 };

 const t = (key) => {
 return translations[language]?.[key] || translations['pt']?.[key] || key;
 };

 return (
 <LanguageContext.Provider value={{ language, changeLanguage, t }}>
 {children}
 </LanguageContext.Provider>
 );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
 return useContext(LanguageContext);
}
